---
version: 2.0

jobs:
  build:
    branches:
      only:
        - develop
    docker:
      - image: fpco/stack-build:lts-11.11
    steps:
      - checkout
      - run:
          name: Build CV
          command: |
            sudo apt-get update
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm install v8.9.4
            npm install hackmyresume -g
            npm install jsonresume-theme-stackoverflow
            hackmyresume build resume.json TO resume.html --theme node_modules/jsonresume-theme-stackoverflow
      - restore_cache:
          keys:
            - stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
            - stack-{{ .Branch }}
            - stack-
      - run:
          name: Setup
          command: stack setup
      - run:
          name: Dependencies
          command: stack build -j2 --dependencies-only
      - save_cache:
          key: stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Build
          command: stack build
      - run:
          name: Generate
          command: stack exec filib-io build
      - run:
          name: Publish
          working_directory: "./_site"
          command: |
            git init
            git config user.name  "CircleCI"
            git config user.email "job@circleci.com"
            git add .
            git commit -m "publish $CIRCLE_SHA1 [ci skip]"
            git push --force https://${GITHUB_ACCESS_TOKEN}@github.com/mcfilib/mcfilib.github.io.git master
